const fs=require("fs")
const{proto}=require("@whiskeysockets/baileys/WAProto")
const{aesDecryptGCM,hmacSign}=require("@whiskeysockets/baileys/lib/Utils/crypto")
const toNumber=t=>typeof t==="object"&&t?("toNumber"in t?t.toNumber():t.low??0):t??0
const asBuf=v=>{if(!v)return Buffer.alloc(0);if(Buffer.isBuffer(v))return v;if(v instanceof Uint8Array)return Buffer.from(v);if(typeof v==="string")return Buffer.from(v,"base64");if(v?.type==="Buffer"&&Array.isArray(v.data))return Buffer.from(v.data);return Buffer.from(v)}
const pickPollMessage=m=>m?.message?.viewOnceMessage?.message||m?.message?.botInvokeMessage?.message||m?.message||null
const pickSecret=(pollCreation,actualPollMsg)=>actualPollMsg?.messageContextInfo?.messageSecret||pollCreation?.message?.botInvokeMessage?.message?.messageContextInfo?.messageSecret||pollCreation?.message?.viewOnceMessage?.message?.messageContextInfo?.messageSecret||pollCreation?.message?.messageContextInfo?.messageSecret||pollCreation?.message?.botInvokeMessage?.message?.pollCreationMessage?.contextInfo?.messageSecret||null
const decryptPollVote=({encPayload,encIv},{pollCreatorJid,pollMsgId,pollEncKey,voterJid})=>{const toBinary=txt=>Buffer.from(txt);const sign=Buffer.concat([toBinary(pollMsgId),toBinary(pollCreatorJid),toBinary(voterJid),toBinary("Poll Vote"),Buffer.from([1])]);const key0=hmacSign(pollEncKey,Buffer.alloc(32),"sha256");const decKey=hmacSign(sign,key0,"sha256");const aad=toBinary(`${pollMsgId}\u0000${voterJid}`);const decrypted=aesDecryptGCM(encPayload,decKey,encIv,aad);return proto.Message.PollVoteMessage.decode(decrypted)}
module.exports=async(snowi,pollMsg)=>{const update=pollMsg?.message?.pollUpdateMessage;if(!update?.pollCreationMessageKey?.id)return;if(!update?.vote?.encPayload||!update?.vote?.encIv)return;const pollCreationKey=update.pollCreationMessageKey;const pollCreation=await snowi.getMessage(pollCreationKey);if(!pollCreation)return;const actualPollMsg=pickPollMessage(pollCreation);if(!actualPollMsg)return;const secret=pickSecret(pollCreation,actualPollMsg);if(!secret)return;const pollEncKeyBuf=asBuf(secret);if(pollEncKeyBuf.length!==32)return;const encPayloadBuf=asBuf(update.vote.encPayload);const encIvBuf=asBuf(update.vote.encIv);const meLid=snowi.user?.lid?`${(snowi.user.lid||"").split(":")[0]}@lid`:"";if(!meLid)return;const isFromMe=pollMsg?.key?.fromMe===true;const remoteJid=pollMsg?.key?.remoteJid||pollCreationKey?.remoteJid||"";const participantLid=pollMsg?.key?.participant||update?.pollCreationMessageKey?.participant||"";const voterJid=isFromMe?meLid:(participantLid&&participantLid.endsWith("@lid")?participantLid:remoteJid);const pollCreatorJid=meLid;let voteMsg;try{voteMsg=decryptPollVote({encPayload:encPayloadBuf,encIv:encIvBuf},{pollEncKey:pollEncKeyBuf,pollCreatorJid,pollMsgId:pollCreationKey.id,voterJid})}catch{return}snowi.ev.emit("messages.update",[{key:pollCreationKey,update:{pollUpdates:[{pollUpdateMessageKey:pollMsg.key,vote:voteMsg,senderTimestampMs:toNumber(update.senderTimestampMs)}]}}])}
let file=require.resolve(__filename)
fs.watchFile(file,()=>{fs.unwatchFile(file);delete require.cache[file];require(file)})
